from __future__ import annotations

FIELD_ALIASES: dict[str, tuple[str, ...]] = {
    "timestamp": (
        "timestamp",
        "event_time",
        "time",
        "@timestamp",
        "date",
        "ts",
        "UtcTime",
    ),
    "source_ip": (
        "source_ip",
        "src_ip",
        "src",
        "client_ip",
        "ClientIP",
        "IpAddress",
        "ip_src",
        "source.address",
        "ip",
    ),
    "dest_ip": (
        "dest_ip",
        "dst_ip",
        "destination_ip",
        "DestinationIp",
        "dest",
        "ip_dst",
        "destination.address",
        "dest_host",
        "dst",
    ),
    "protocol": ("protocol", "proto", "network_protocol", "Protocol", "service"),
    "action": ("action", "decision", "outcome", "event_action", "Operation", "OperationName", "event", "status"),
    "threat_label": ("threat_label", "label", "classification", "threat_class", "RiskLevel", "RiskState", "severity"),
    "log_type": ("log_type", "source_type", "category", "event_category", "source", "log_source"),
    "bytes_transferred": ("bytes_transferred", "bytes", "bytes_out", "transfer_bytes", "orig_bytes", "resp_bytes"),
    "user_agent": ("user_agent", "ua", "http_user_agent", "ClientAppUsed"),
    "request_path": ("request_path", "path", "uri", "url_path", "http_uri", "QueryName", "file"),
    "subject": ("subject", "email_subject"),
    "body": ("body", "message", "email_body", "raw_message", "text", "CommandLine", "notes"),
    "urls": ("urls", "url", "link", "links"),
    "host": ("host", "hostname", "device", "agent_host", "runner_host"),
    "app": ("app", "application", "program"),
    "user_id": ("user_id", "user", "username", "principal", "User", "UserId", "UserPrincipalName"),
    "email": ("email", "sender", "from", "UserPrincipalName"),
}
